### ISSUE TITLE
is there anything similar to WayNode Type in osm library?

### ISSUE THREAD

**Issue by alinakhaee** [woltapp/parallelpbf#19]
hi. <br>
The original osm dependency for Java has a type called `WayNode`. which is a simple `nodeId` with latitude and longitude of the node. <br>
In addition to the `List<Node> nodes;` that each `Way` has, in osm library the `Way` type also has a `List<WayNode> wayNodes;`. <br>
can you guys please add this field to the `Way` class or it is not possible?

**Comment by willtemperley** [comment]
OSM protobuf files are very normalised, i.e. node attributes such as coordinates are stored on the nodes themselves, separate from ways. You need to retrieve this information yourself.  Personally I use two passes over the file, first to filter the ways of interest and second to add the coordinate information to the way, but there are many ways to do this.

**Comment by akashihi** [comment]
As @willtemperley explained, nodes and ways are stored separately in the OSM PBF files and there is no simple way to reconstruct ways geometry while reading the file. You'll need to cache nodes geometry while reading, cache lists of nodes for ways and after finishing the file you'll be able to reconstruct the geometry yourself.
