### ISSUE TITLE
Version 0.3.0 missing in maven

### ISSUE THREAD

**Issue by akamuza** [woltapp/parallelpbf#2]
I cannot add this dependency to my project as 0.3.0 version is missing in maven: https://mvnrepository.com/artifact/com.wolt.osm/parallelpbf
When I try 0.2.0 - then **crosby.binary:osmpbf:1.2.1** is missing.

I've tried maven, jcenter and google repositories.

**Comment by akashihi** [comment]
Looks like i'm sing some non-standard repository here:( ill check on this week and either fix or provide some documented workaround
